### ISSUE TITLE
При внедрении в проект Allure не появляется папка build/reports/allureReport

### ISSUE THREAD

**Issue by marinaolivekey** [marinaolivekey/aqaPatterns#5]
# Описание
При внедрении в проект Allure не появляется папка build/reports/allureReport

# Локация дефекта
https://github.com/marinaolivekey/aqaPatterns

# Шаги воспроизведения
1) В проекте был изменен   build.gradle 
https://github.com/marinaolivekey/aqaPatterns/blob/ff7dc08b606b2405ac9d155a6f2cac67e29c0c92/build.gradle#L4

2) добавлены аннтотации бефор олл и афтер олл
https://github.com/marinaolivekey/aqaPatterns/blob/ff7dc08b606b2405ac9d155a6f2cac67e29c0c92/src/test/java/DateChangeTest.java#L21

3) импортирован аллур
https://github.com/marinaolivekey/aqaPatterns/blob/ff7dc08b606b2405ac9d155a6f2cac67e29c0c92/src/test/java/DateChangeTest.java#L12

4) запущен джарник
 java -jar ./artifacts/app-replan-delivery.jar

5) запущены тесты
./gradlew test

# _Ожидаемый результат_ 
появляется папка build/reports/allureReport

# _Фактический результат_ 
не появляется папка build/reports/allureReport

# Окружение
Операционная система macOS 13.6.4 (22G513)
IDE IntelliJ IDEA 2021.1.3 (Community Edition)
JAVA OpenJDK 11

<img width="1176" alt="Screenshot 2024-06-09 at 12 55 21" src="https://github.com/marinaolivekey/aqaPatterns/assets/88292001/a1c3b9ad-e34f-48b0-b1e5-3a7e59d70e56">

**Comment by andrew-pahomov** [comment]
Не вижу шагов для генерации отчетов, запуска тестов для получения отчета недостаточно.     
![image](https://github.com/marinaolivekey/aqaPatterns/assets/59327373/cb7ee8f4-a2e1-44b7-800c-401c6ebe4a6e)
